services:
  _defaults:
    public: true


  infra.json_rpc_params_validator.listener.validate_jsonrpc_params:
    class: Yoanm\SymfonyJsonRpcParamsValidator\Listener\JsonRpcValidateParamsListener
    arguments: ['@json_rpc_params_sf_validator_sdk.validator']
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_server_skd.validate_params'
        method: '__invoke'

  json_rpc_params_validator.listener.jsonrpc_doc_method_created:
    class: Yoanm\SymfonyJsonRpcParamsValidator\Listener\MethodDocCreatedListener
    arguments:
      - '@json_rpc_params_sf_validator_sdk.doc.tranformer'
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_http_server.method_doc_created'
        method: 'enhanceMethodDoc'
